### ISSUE TITLE
Vytvoření class diagramu

### ISSUE THREAD

**Issue by tousekdominik** [tousekdominik/ODSKartSharp#16]
* Vygenerovat class diagram z interfaců ve VSProjektu

**Comment by tousekdominik** [comment]
Rozřezaný class diagram vytvořen a připraven k připomínkám ve složce trunk/Diagrams/

**Comment by voglovaMiroslava** [comment]
K enumu ODSImportResult: Není zcela jasné co značí "CorruptedFile". Pokud to má značit, že se nepovedlo ODS rozbalit a tedy, že se asi nejedená o ODS, pak bych to nazvala trochu jinak. Například NotODS.
K UserInfo: Je opravdu Id potřeba, když UserName musí být jedinečné (jak vyplývá z metody UsernameAlreadyExists)?

**Comment by tousekdominik** [comment]
K enumu ODSImportResult: To je pravda. Už jsem to opravil na Success, NotODS a NotValid
K UserInfo: Id i username jsou obě jedinečné. Proto Id je redundantní informace a možná i nepotřebný syntetický klíč. Změním to. Mělo by to smysl akorát ve chvíli, kdy bychom umožnili změnu uživatelského jména. Což ale není dobrý nápad, protože je na něj vázán adresář s daty uživatele, který by musel být jinak vázán na Id.
