### ISSUE TITLE
Vytvoření základní layout šablony pro projekt

### ISSUE THREAD

**Issue by tousekdominik** [tousekdominik/ODSKartSharp#2]
Zahrnuje vytvoření souboru _Layout.html, který představuje základní šablonu pro všechny  webové stránky. Bude obsahovat hlavní menu s odkazy:
* Spravovat
* Rychlý náhled
* Nahrát
* Stáhnout
* Nová

Pořadí odkazů nechávám Vašem uvážení tak, aby nejčastěji přistupované odkazy byly nejlépe dostupné a menu bylo logicky uspořádáno.

Cesty v odkazech nejsou nyní důležité - změní se při oživování šablony

Menu bude dále obsahovat Informaci o přihlášeném uživateli. Například: "Přihlášen jako: xticha"
Pro označení obsahu - místo kam se budou vkládat šablony dalších stránek použijte "tag" <!-CONTENT-!>.

Poslední věc co bude šablona obsahovat je patička, která bude obsahovat informaci o copyrightu a názvu produktu.

https://drive.google.com/folderview?id=0BxPNAczAKgRHfnhBOTVXYlM5dnZGWFNpUVFBaG80VUZDUDlBYm0zQmhZM1Vrdmt4SDZlcXM&usp=sharing
<b>Grafický náhled č . 12</b>

**Comment by TerezaT** [comment]
Layout už je hotový ve složce graphics, akorát ještě dolaďuji efekty s textem.
