### ISSUE TITLE
Uživatelský manuál ke struktuře nahrávaného ODS dokumentu

### ISSUE THREAD

**Issue by tousekdominik** [tousekdominik/ODSKartSharp#21]
Uživatelský manuál v nějakém rozumném formátu (prozatím docx nebo pdf nejlépe obě verze) prosím uložit do složky 'trunk\AssignmentMaterials\ODSUserManual'

* manuál by měl obsahovat pokyny pro uživatele o tom, jak má vypadat ODS dokument(kde mají být data umístěna, jak dokument strukturovat, ... ), který pak může bez problému do aplikace nahrát a následně s ním pomocí aplikace pracovat.

**Comment by dmaxa** [comment]
Manuál vytvořen, issue zavřeno.

**Comment by dmaxa** [comment]
Manuál vytvořen, issue zavřeno.
