### ISSUE TITLE
Zapomenuté heslo

### ISSUE THREAD

**Issue by tousekdominik** [tousekdominik/ODSKartSharp#25]
<h2>Popis</h2>
Stránka umožňující uživateli obnovit zapomenuté heslo, přejít na stránku s registrací, nebo přejít na stránku pro přihlášení

<h2>Logika</h2>
* Po stisku tlačítka "obnovit" se v controlleru ověří, zda existuje uživatelský účet pro zadané jméno, pokud ano, zkontroluje se, zda zadaný e-mail koresponduje s e-mailem evidovaným v profilu, následně se pro daný účet vygeneruje nové náhodné heslo, uloží se do uživatelského účtu a na e-mail se uživateli zašle oznámení o úspěšném/neúspěšném pokusu o obnovu hesla spolu s novým heslem a přesměruje se na stránku pro přihlášení - předmětem issue #26
* Po stisku odkazu "Přihlásit se" se přesměruje na stránku pro přihlášení - předmětem issue #26
* Po stisku odkazu "Registrace" se přesměruje na stránku pro registraci - předmětem issue #27

<h2>Implementace</h2>
* Controller pro zpracování požadavků
* View pro zobrazení a práci s daty(ForgottenPassword)
* Pro práci s uživatelskými účty použijte rozhraní Models/Autentization/IAutentization(dokud nebude plně doimplementováno), pro práci s adresáři uživatele a uživatelskými účty použijte manager Models/Managers/UserInfoManager a <b>pro procházení adresářovou strukturou pokud možno využijte Models/UserStorage/Storage na místo absolutních cest.</b>
* Každý manager dostává při vytváření v konstruktoru instanci IStorage, která reprezentuje uložiště dat aktuálního uživatele. Třída storage implemenována zde: Models/UserStorage/Storage.cs 

<h2>Hinty</h2>
C#/.net MVC má již zabudované metody na zpracování příchozích požadavků, takže parametry předpřipraví a předá je zpracovávací metodě v controlleru do parametrů pokud mají parametry odpovídající datový typ.

V C#/.net MVC je k dispozici jazyk Razor, který ulehčuje práci s Views a dodává jim funkce pro práci s daty. Např.: HTML helpers, které by zde bylo vhodné použít pro tvorbu odkazů.

<b>Grafické návrhy: </b> https://drive.google.com/folderview?id=0BxPNAczAKgRHfnhBOTVXYlM5dnZGWFNpUVFBaG80VUZDUDlBYm0zQmhZM1Vrdmt4SDZlcXM&usp=sharing
<b>Číslo návrhu pro tuto issue: </b> 10

**Comment by voglovaMiroslava** [comment]
Napsáno, otestováno, nutno dodělat styl.
