### ISSUE TITLE
Login/Úvodní obrazovka

### ISSUE THREAD

**Issue by tousekdominik** [tousekdominik/ODSKartSharp#26]
<h2>Popis</h2>
Stránka umožňující uživateli se přihlásit, přejít na stránku s registrací, nebo přejít na stránku pro obnovu zapomenutého hesla

<h2>Logika</h2>
* Po stisku tlačítka přihlásit a obsloužení controllerem se přesměruje na stránku "Spravovat"
* Po stisku odkazu "Zapomenuté heslo" se přesměruje na stránku pro obnovu zapomenutého hesla - předmětem issue #25
* Po stisku odkazu "Registrace" se přesměruje na stránku pro registraci - předmětem issue #27 
"Spravovat" - <b>Grafický návrh č. 07</b> (předmětem jiné issue)

<h2>Implementace</h2>
* Controller pro zpracování požadavků
* View pro zobrazení a práci s daty(Login)
* Pro práci s uživatelskými účty použijte rozhraní Models/Autentization/IAutentization(dokud nebude plně doimplementováno), pro práci s adresáři uživatele a uživatelskými účty použijte manager Models/Managers/UserInfoManager a <b>pro procházení adresářovou strukturou pokud možno využijte Models/UserStorage/Storage na místo absolutních cest.</b>
* Každý manager dostává při vytváření v konstruktoru instanci IStorage, která reprezentuje uložiště dat aktuálního uživatele. Třída storage implemenována zde: Models/UserStorage/Storage.cs 

<h2>Hinty</h2>
C#/.net MVC má již zabudované metody na zpracování příchozích požadavků, takže parametry předpřipraví a předá je zpracovávací metodě v controlleru do parametrů pokud mají parametry odpovídající datový typ.

V C#/.net MVC je k dispozici jazyk Razor, který ulehčuje práci s Views a dodává jim funkce pro práci s daty. Např.: HTML helpers, které by zde bylo vhodné použít pro tvorbu odkazů.

<b>Grafické návrhy: </b> https://drive.google.com/folderview?id=0BxPNAczAKgRHfnhBOTVXYlM5dnZGWFNpUVFBaG80VUZDUDlBYm0zQmhZM1Vrdmt4SDZlcXM&usp=sharing
<b>Číslo návrhu pro tuto issue: </b> 1

**Comment by voglovaMiroslava** [comment]
Napsáno, otestováno, nutno dodělat styl.
