### ISSUE TITLE
Registrace uživatele

### ISSUE THREAD

**Issue by tousekdominik** [tousekdominik/ODSKartSharp#27]
<h2>Popis</h2>
Stránka umožňující uživateli zaregistrovat se, přejít na stránku pro obnovu hesla, nebo přejít na stránku pro přihlášení

<h2>Logika</h2>
* Po stisku tlačítka "registrovat" se v controlleru ověří, zda již uživatelský účet pro zadané jméno neexistuje, pokud ano registrace neproběhne a uživateli bude umožněno provést registraci znovu s jinými údaji. Poku v systému dané jméno ještě neexistuje, zadaná hesla souhlasí a byl zadán validní e-mail, proběhne registrace uživatele, uživatel se přihlásí a přesměruje na stránku "Spravovat"
* Po stisku odkazu "Přihlášení" se přesměruje na stránku pro přihlášení - předmětem issue #26
"Spravovat" - Grafický návrh č. 07 (předmětem jiné issue)

<h2>Implementace</h2>
* Controller pro zpracování požadavků
* View pro zobrazení a práci s daty(Register)
* Pro práci s uživatelskými účty použijte rozhraní Models/Autentization/IAutentization(dokud nebude plně doimplementováno), pro práci s adresáři uživatele a uživatelskými účty použijte manager Models/Managers/UserInfoManager a <b>pro procházení adresářovou strukturou pokud možno využijte Models/UserStorage/Storage na místo absolutních cest.</b>
* Každý manager dostává při vytváření v konstruktoru instanci IStorage, která reprezentuje uložiště dat aktuálního uživatele. Třída storage implemenována zde: Models/UserStorage/Storage.cs 

<h2>Hinty</h2>
C#/.net MVC má již zabudované metody na zpracování příchozích požadavků, takže parametry předpřipraví a předá je zpracovávací metodě v controlleru do parametrů pokud mají parametry odpovídající datový typ.

V C#/.net MVC je k dispozici jazyk Razor, který ulehčuje práci s Views a dodává jim funkce pro práci s daty. Např.: HTML helpers, které by zde bylo vhodné použít pro tvorbu odkazů.

<b>Grafické návrhy: </b> https://drive.google.com/folderview?id=0BxPNAczAKgRHfnhBOTVXYlM5dnZGWFNpUVFBaG80VUZDUDlBYm0zQmhZM1Vrdmt4SDZlcXM&usp=sharing
<b>Číslo návrhu pro tuto issue: </b> 02

**Comment by voglovaMiroslava** [comment]
Napsáno, otestováno, nutno dodělat styl.
