### ISSUE TITLE
Vytvoření grafických prvků

### ISSUE THREAD

**Issue by tousekdominik** [tousekdominik/ODSKartSharp#33]
<h2>Prvky k vytvoření</h2>
* Popelnice -> pro návrh 07
* Instalatérský klíč/šroubovák a kladivo  -> pro návrh 07
* "plus" tlačítko -> pro návrh 07
* "plus" tlačítko -> pro návrh 09
* "x" tlačítko -> pro návrh 09

<h3>Grafické návrhy</h3>
https://drive.google.com/folderview?id=0BxPNAczAKgRHfnhBOTVXYlM5dnZGWFNpUVFBaG80VUZDUDlBYm0zQmhZM1Vrdmt4SDZlcXM&usp=sharing

<b>Výsledek práce uložte do adresáře:</b> <i>'trunk\AssignmentMaterials\Graphics'</i>

**Comment by TerezaT** [comment]
Byly nahrány 4 ikonky ve formátu gif pro zachování transparency, pokud by byl problém s formátem, nahrála jsem i jejich rozpracované verze ve Photoshopu CS2.
