### ISSUE TITLE
CRUD operace nad médii a kategoriemi

### ISSUE THREAD

**Issue by tousekdominik** [tousekdominik/ODSKartSharp#4]
* Vytvoření manageru pro práci s médii.
* Vytvoření manageru pro práci s kategoriemi.

Nutno implementovat rozhraní:
* Models/Managers/ICategoryManager -> CategoryManager
* Models/Managers/IMediaManager -> MediaManager

Entitní třídy:
* Models/Entities/Category
* Models/Entities/Media

**Comment by voglovaMiroslava** [comment]
Media manager napsán, ještě netestován.

**Comment by voglovaMiroslava** [comment]
Implementováno. Testováno.
