### ISSUE TITLE
Vyhledávání záznamu v kartotéce

### ISSUE THREAD

**Issue by tousekdominik** [tousekdominik/ODSKartSharp#7]
i.	Dle ID média
ii.	Dle názvu kategorie
iii.	Dle názvu média – Fulltextově
iv.	Dle názvu kategorie (přesná shoda) + názvu média (Fulltext)

* Je nutné implementovat rozhraní 'Search/IMediaSearcher'
* Pro implementaci je třeba využít třídy MediaManager a CategoryManager (ad issue "CRUD operace nad médii a kategoriemi #4")
* Práce se záznamy možná za použití LinQ dotazů

**Comment by voglovaMiroslava** [comment]
Implementováno, otestováno.
